# nginx
FROM nginx:stable

RUN rm /etc/localtime \
  && echo "Asia/Tokyo" > /etc/timezone \
  && dpkg-reconfigure -f noninteractive tzdata

#デフォルトのnginxファイルを削除
RUN rm -f /etc/nginx/conf.d/*

COPY ./nginx/pashacon.conf /etc/nginx/conf.d/pashacon.conf

#-c以降の設定ファイルを指定して起動 daemon offでフォアグラウンドで起動
CMD /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf